FROM golang:1.21 AS build
WORKDIR /usr/src/app
ENV CGO_ENABLED=0

COPY . .
RUN go build -v -o /usr/local/bin/app ./cmd/server

# Stage 2: Create the final runtime image
FROM alpine:3.19
COPY --from=build /usr/local/bin/app .
CMD ["./app"]
